### ISSUE TITLE
thx for this!

### ISSUE THREAD

**Issue by karelbilek** [teacat/noire#4]
Hey thanks for this, it seems simple and to the point.

No offense, the comments/docs could be in English :D my ~zhong-guo~ zhong-wen (see?) is quite bad.. but the code is so clear that it's ok

**Comment by YamiOdymel** [comment]
A message like this made my day, I've also changed the documentation and the in-code comments from Chinese to English.

Though it does have some critical grammar issues but it's still better than reading 齏蚕蠿龘羃齏澷譱鷆齅黱.

**Comment by karelbilek** [comment]
No prob.

It was not needed - again, the code speaks for itself a lot :D - but yeah double thanks.
